export const REACTIONS: string[] = [
  "https://i.imgur.com/LXTZgAr.png",
  "https://i.imgur.com/2oV2V2j.png",
  "https://i.imgur.com/UsdGaBY.png",
  "https://i.imgur.com/XqP4yey.jpg",
  "https://i.imgur.com/xxJKZlt.png",
  "https://i.imgur.com/wRGykYI.png",
  "https://i.imgur.com/5JPqNnK.jpg",
  "https://i.imgur.com/i4QPL6t.png",
  "https://i.imgur.com/CxsaHzp.png",
  "https://i.imgur.com/RfP9uwW.png",
  "https://i.imgur.com/AMsbKN6.png",
  "https://i.imgur.com/c8EtDN2.png",
  "https://i.imgur.com/ERYqTqK.png",
  "https://i.imgur.com/7PreQ8X.png",
  "https://i.imgur.com/sQMTsq1.jpg",
  "https://i.imgur.com/HzxVw49.png",
  "https://i.imgur.com/c0t4vBL.png",
  "https://i.imgur.com/lWqqenz.png",
  "https://i.imgur.com/UXlT9Vj.png",
  "https://i.imgur.com/seES1jf.png",
  "https://i.imgur.com/F7iYQRs.jpg",
  "https://i.imgur.com/jPbLYfQ.png",
  "https://i.imgur.com/3tfiHcc.png",
  "https://i.imgur.com/zfuF4OM.png",
  "https://i.imgur.com/fHLtHSs.jpeg",
  "https://i.imgur.com/QEAmqf8.png",
  "https://i.imgur.com/g43fhXV.png",
  "https://i.imgur.com/vNVI7lO.png",
  "https://i.imgur.com/MRuyQic.jpeg",
  "https://i.imgur.com/4tH6QH5.jpeg",
  "https://i.imgur.com/vqLDs2P.jpeg",
  "https://i.imgur.com/2SKrAsD.jpeg",
  "https://i.imgur.com/0EkJbBj.jpeg",
  "https://i.imgur.com/lSJDFQq.png",
  "https://i.imgur.com/pkoXtqD.jpeg",
  "https://i.imgur.com/SVPEcxK.jpeg",
  "https://i.imgur.com/vKR5MVX.png",
  "https://i.imgur.com/tCzN1Y1.png",
  "https://i.imgur.com/Fy8uJcT.png",
  "https://i.imgur.com/gGzMpqg.jpeg",
  "https://i.imgur.com/9BvlX9b.png",
  "https://i.imgur.com/ShInjZm.jpeg",
  "https://i.imgur.com/Ws1WAb2.jpeg",
  "https://i.imgur.com/Q55IOOA.png",
  "https://i.imgur.com/0IboiWo.jpeg",
  "https://i.imgur.com/pVHl3d6.jpeg",
  "https://i.imgur.com/IdhkHm6.png",
  "https://i.imgur.com/1z3jdeY.png",
  "https://i.imgur.com/HUE9tDB.jpeg",
  "https://i.imgur.com/i1ULeRq.png",
  "https://i.imgur.com/ss3GsmQ.gif",
  "https://i.imgur.com/nyZJRui.png",
];

export const RESPONSE_COLOR: number = 0xbf40bf;

export const LEADERBOARD_EMOJIS: string[] = [
  "<a:catjam:1251597146642317312>",
  "<:gladbrosnan:1452712767055204563>",
  "<:goodforyou:1251389543333236798>",
  "<:okcoolbuddy:1251609588453609552>",
  "<:kek:1251494676960247829>",
];

export const QUOTE_EMBED_TITLES: string[] = [
  "Wise words to heed",
  "Really makes you think",
  "I didn't really think of it that way",
  "Well, when you put it that way",
  "That really gets the neurons firing!",
];
